Fix test execution
For some reason, opentest4j was not added as a dependency, resulting with

```
com.automattic.encryptedloggingintellij.MyPluginTest > initializationError FAILED
    java.lang.NoClassDefFoundError at ClassLoader.java:-2
        Caused by: java.lang.ClassNotFoundException at UrlClassLoader.java:233
```